  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hey
  template:
    metadata:
      labels:
        app: hey
    spec:
      containers:
      - image: ramiro/hey
        name: hey
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
        fsGroup: 1000

---

apiVersion: v1
kind: Service
metadata:
  name: hey
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "hey"
    port: 8080
  selector:
    app: hey